name: C/C++ CI based on CMake

on:
  push:
  pull_request:

jobs:
  cmake_build:
    name: CMake + Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          submodules: true
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt update
          sudo apt install -y cmake build-essential pybind11-dev
          cmake --version
          cc --version
          c++ --version
          python --version
      - name: Build and install XCDF with Python bindings
        run: |
          echo "Installing dependencies"
          sudo apt update
          sudo apt install -y cmake build-essential pybind11-dev
          echo "Tools versions"
          cmake --version
          cc --version
          c++ --version
          python --version
          echo "Configuring...."
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=~/.local/xcdf
          echo "Building...."
          cmake --build build -- -j 2
          echo "Installing..."
          cmake --install build
      - name: Test suite
        run: |
          cd build
          make test
