name: Python-based CI

on:
  push:
  pull_request:

jobs:
  cmake_build:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          submodules: true
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build with scikit-build
        run: |
          pip install ".[tests]"
          python -c "from xcdf import __version__; print(f'XCDF python bindings v{__version__}')"
          pytest
